app:
  host: localhost
  port: 8080
  debug: True
data:
  aspects:
    - FOOD#QUALITY
    - SERVICE#GENERAL
    - RESTAURANT#PRICES
    - AMBIENCE#GENERAL
    - RESTAURANT#GENERAL
    - FOOD#STYLE_OPTIONS
  sentiments:
    - neutral
    - negative
    - positive
  tune-file: lib/data/sentence_level/tune.json

