app:
  host: localhost
  port: 8080
  debug: True
data:
  aspects:
    - RESTAURANT#MISCELLANEOUS
    - FOOD#QUALITY
    - RESTAURANT#GENERAL
    - DRINKS#QUALITY
    - AMBIENCE#GENERAL
    - SERVICE#GENERAL
    - FOOD#PRICES
    - RESTAURANT#PRICES
    - FOOD#STYLE_OPTIONS
    - DRINKS#PRICES
    - DRINKS#STYLE_OPTIONS
    - LOCATION#GENERAL
  sentiments:
    - neutral
    - conflict
    - negative
    - positive
  tune-file: lib/data/sentence_level/tune.json

